# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Mod properties
mod_version = 4.1.0
maven_group = dev.boxadactle
archives_name = macrocraft
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.2

# Dependencies
fabric_loader_version = 0.19.3
fabric_api_version = 0.154.2+26.2
neoforge_version = 26.2.0.8-beta

boxlib_version=22.0.1
modmenu_version=20.0.0-beta.4

# publishing
game_versions = 26.2
project_id_curseforge = 1007092
project_id_modrinth = iqX9hVyP
release_type = release
