modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "macrocraft"
version = "${version}"
displayName = "MacroCraft"
authors = "Boxadactle"
description = '''
MacroCraft is a revolutionary mod that empowers players to record, save, and execute complex sequences of actions with unparalleled ease.
'''
logoFile = "icon.png"

[[dependencies.macrocraft]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.8-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.macrocraft]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,27)"
ordering = "NONE"
side = "BOTH"

[[dependencies.macrocraft]]
modId = "boxlib"
type = "required"
versionRange = "[22.0.1,23.0.0)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "macrocraft.mixins.json"
